### ISSUE TITLE
dose it support arm

### ISSUE THREAD

**Issue by slowpy** [laanwj/dwarf_to_c#2]
First this is a great product.
When I use this for arm,I got same problem. Index error in info init .attr_index

Little Endian or Big Endian

**Comment by laanwj** [comment]
ARM should work, though I have never tried big endian. Your report is lacking, though.
Can you send me the executable and full output at laanwj@gmail.com? ([GPG key](https://laanwj.github.io/assets/2016/05/06/initial/laanwj.gpg))

**Comment by slowpy** [comment]
yes, this commit fix my problem
DW_FORM_sec_offset is always 4 bytes
https://github.com/laanwj/dwarf_to_c/commit/ccdc482ddd0dd2cd18c4b273e7bd6163954af0e5
